using System.IO;
using MiniBrawl.Gameplay.Player;
using MiniBrawl.Gameplay.VFX;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

/// <summary>
/// Renders a scene to a PNG from the command line.
///
/// The scenes are generated by code and reviewed as code, which leaves one question code review
/// cannot answer: whether the result came out the size it was meant to be. A build takes six
/// minutes and a phone; this takes seconds.
///
/// TRUST THE LOG, NOT THE PICTURE. In batchmode every sprite renders with the same texture bound,
/// so the image shows the right shapes at the right sizes wearing each other's textures. The
/// per-renderer report is accurate, and is what caught a particle sized four world units instead
/// of one after two earlier attempts at deriving pixels-per-unit had both failed silently. The PNG
/// is a layout check; judging how the art actually looks needs a real player on a real device.
///
/// Run without -nographics: there has to be a graphics device to render with.
/// </summary>
public static class SceneSnapshot
{
    [MenuItem("MiniBrawl/Snapshot Prototype Scene")]
    public static void Prototype() => Capture("Assets/_Project/Scenes/10_Prototype.unity");

    public static void Network() => Capture("Assets/_Project/Scenes/20_Network.unity");

    static void Capture(string scenePath)
    {
        string output = Path.GetFullPath(CommandLineArg("-snapshotOut")
                                         ?? "Builds/snapshot.png");
        int width = 1280, height = 720;

        EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);

        /* Edit mode never calls LateUpdate, so the sprite rig sits at its prefab defaults. Posing
         * it by hand here is the difference between a picture of the scene and a picture of the
         * game: aim, thrust and a walk frame are exactly the states worth checking. */
        PoseForCamera();

        Camera camera = Camera.main;
        if (camera == null)
        {
            Debug.LogError("[SceneSnapshot] No main camera.");
            return;
        }

        var target = new RenderTexture(width, height, 24, RenderTextureFormat.ARGB32)
        {
            antiAliasing = 1,
        };

        RenderTexture previous = camera.targetTexture;
        camera.targetTexture = target;
        camera.Render();

        RenderTexture active = RenderTexture.active;
        RenderTexture.active = target;

        var image = new Texture2D(width, height, TextureFormat.RGBA32, false);
        image.ReadPixels(new Rect(0, 0, width, height), 0, 0);
        image.Apply();

        RenderTexture.active = active;
        camera.targetTexture = previous;

        Directory.CreateDirectory(Path.GetDirectoryName(output));
        File.WriteAllBytes(output, image.EncodeToPNG());

        Object.DestroyImmediate(image);
        target.Release();
        Object.DestroyImmediate(target);

        Debug.Log($"[SceneSnapshot] Wrote {output} ({width}x{height}) from {scenePath}.");
        ReportRenderers();
    }

    /// <summary>
    /// Names every sprite and its world size. Reading this off the rendered pixels is guesswork —
    /// a tinted particle at four times its intended size looks a lot like a different sprite
    /// altogether, which is exactly the mistake this is here to stop.
    /// </summary>
    static void ReportRenderers()
    {
        foreach (SpriteRenderer sr in Object.FindObjectsByType<SpriteRenderer>(FindObjectsSortMode.None))
        {
            string sprite = sr.sprite != null ? sr.sprite.name : "<none>";
            Vector2 size = sr.sprite != null ? sr.sprite.bounds.size : Vector2.zero;
            Texture tex = sr.sprite != null ? sr.sprite.texture : null;
            string texName = tex != null ? $"{tex.name} {tex.width}x{tex.height}" : "<none>";

            Debug.Log($"[SceneSnapshot]   {sr.gameObject.name,-12} sprite={sprite,-22} " +
                      $"spriteUnits={size.x:0.00}x{size.y:0.00} tex={texName}");
        }
    }

    /// <summary>Puts the player into a pose worth looking at, since nothing is simulating one.</summary>
    static void PoseForCamera()
    {
        foreach (PlayerVisual visual in Object.FindObjectsByType<PlayerVisual>(FindObjectsSortMode.None))
        {
            if (visual.Skins.Length > 0 && visual.Body != null)
            {
                PlayerVisual.Skin skin = visual.Skins[0];
                visual.Body.sprite = skin.Walk != null && skin.Walk.Length > 0
                    ? skin.Walk[0]
                    : skin.Stand;
                visual.Body.transform.localPosition = new Vector3(0f, -PlayerMotor.Size.y * 0.5f, 0f);
            }

            if (visual.Gun != null)
            {
                visual.Gun.transform.localPosition = new Vector3(0f, -0.05f, 0f);
                visual.Gun.transform.localRotation = Quaternion.Euler(0f, 0f, 25f);
            }

            if (visual.Jet != null)
            {
                visual.Jet.enabled = true;
                visual.Jet.color = new Color(1f, 0.6f, 0.25f, 0.9f);
                visual.Jet.transform.localScale = new Vector3(visual.JetScale.x, visual.JetScale.y, 1f);
            }

            if (visual.Muzzle != null)
            {
                visual.Muzzle.enabled = true;
                visual.Muzzle.color = new Color(1f, 0.9f, 0.55f, 1f);
                visual.Muzzle.transform.localScale = Vector3.one * visual.MuzzleScale;
            }
        }
    }

    static string CommandLineArg(string name)
    {
        string[] args = System.Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
            if (args[i] == name) return args[i + 1];

        return null;
    }
}
